from typing import Protocol
from src.courier.domain.entities.courier_profile import CourierProfile
import uuid

class ICourierProfileRepository(Protocol):
    async def get_courier_by_id(self, profile_id: uuid.UUID) -> CourierProfile | None:
        ...
    async def get_courier_by_account_id(self, account_id: uuid.UUID) -> CourierProfile | None:
        ...
    async def add_courier(self, profile: CourierProfile) -> None:
        ...
    async def update_courier(self, profile: CourierProfile) -> None:
        ...
    async def delete_courier(self, account_id: uuid.UUID) ->  None:
        ...

class IUnitOfWork(Protocol):
    courier_profiles: ICourierProfileRepository

    async def __aenter__(self):
        ...
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        ...
    async def commit(self):
        ...
    async def rollback(self):
        ...