import uuid
from typing import Any, Protocol, Self

from src.identity.application.dtos.oauth_user import OAuthUser
from src.identity.application.dtos.token_pair import TokenPair
from src.identity.domain.entities.account import Account
from src.identity.domain.entities.OTP import OTP
from src.identity.domain.entities.refresh_token import RefreshToken
from src.identity.domain.entities.user_profile import UserProfile
from src.identity.domain.value_objects.email import Email
from src.identity.domain.value_objects.phone_number import PhoneNumber
from src.outbox.application.interfaces import IOutboxRepository


class IOTPRepository(Protocol):
    async def save_otp(self, otp: OTP) -> None: ...
    async def get_otp_by_session(self, session_id: uuid.UUID) -> OTP | None: ...
    async def get_latest_otp_by_phone(self, phone: PhoneNumber) -> OTP | None: ...
    async def update_otp(self, otp: OTP) -> None: ...


class IRefreshTokenRepository(Protocol):
    async def save_refresh_token(self, token: RefreshToken) -> None: ...
    async def get_refresh_token(self, refresh_token: str) -> RefreshToken | None: ...


class ITokenGenerator(Protocol):
    def generate_pair(self, account_id: uuid.UUID) -> TokenPair: ...


class ITokenValidator(Protocol):
    def validate_access_token(self, token: str) -> dict[str, Any]: ...
    def validate_refresh_token(self, token: str) -> dict[str, Any]: ...


class IAccountRepository(Protocol):
    async def get_account_by_id(self, account_id: uuid.UUID) -> Account | None: ...
    async def get_account_by_phone(self, phone_number: PhoneNumber) -> Account | None: ...
    async def get_account_by_email(self, email: Email) -> Account | None: ...
    async def add_account(self, account: Account) -> None: ...
    async def update_account(self, account: Account) -> None: ...
    async def delete_account(self, account_id: uuid.UUID) -> None: ...


class IUserProfileRepository(Protocol):
    async def get_user_by_id(self, profile_id: uuid.UUID) -> UserProfile | None: ...
    async def get_user_by_account_id(self, account_id: uuid.UUID) -> UserProfile | None: ...
    async def add_user(self, profile: UserProfile) -> None: ...
    async def update_user(self, profile: UserProfile) -> None: ...
    async def delete_user(self, profile_id: uuid.UUID) -> None: ...


class IUnitOfWork(Protocol):
    otp: IOTPRepository
    refresh_tokens: IRefreshTokenRepository
    accounts: IAccountRepository
    user_profiles: IUserProfileRepository
    outbox: IOutboxRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class IOAuthService(Protocol):
    def get_authorization_url(self, state: str) -> str: ...
    async def get_user_info(self, code: str) -> OAuthUser: ...


class ICacheRepository(Protocol):
    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl_second: int = 600) -> None: ...
    async def delete(self, key: str) -> None: ...


class IOAuthServiceFactory(Protocol):
    def get_service(self, provider: str) -> IOAuthService: ...
